// Data Store
const products = [
    {
        id: 1,
        name: "Royal Gold Serum",
        category: "cosmetics",
        price: "€89,00",
        image: "http://static.photos/cosmetic/640x360/1",
        badge: "Bestseller"
    },
    {
        id: 2,
        name: "Dutch Glow Cream",
        category: "beauty",
        price: "€65,00",
        image: "http://static.photos/cosmetic/640x360/2",
        badge: "Novo"
    },
    {
        id: 3,
        name: "Performance Whey Pro",
        category: "gym",
        price: "€55,00",
        image: "http://static.photos/gym/640x360/3",
        badge: null
    },
    {
        id: 4,
        name: "Wellness Collagen",
        category: "wellness",
        price: "€45,00",
        image: "http://static.photos/cosmetic/640x360/4",
        badge: "Popular"
    },
    {
        id: 5,
        name: "Night Repair Oil",
        category: "cosmetics",
        price: "€78,00",
        image: "http://static.photos/cosmetic/640x360/5",
        badge: null
    },
    {
        id: 6,
        name: "Vitamin Complex",
        category: "wellness",
        price: "€35,00",
        image: "http://static.photos/medical/640x360/6",
        badge: null
    },
    {
        id: 7,
        name: "Pre-Workout Elite",
        category: "gym",
        price: "€42,00",
        image: "http://static.photos/gym/640x360/7",
        badge: "Novo"
    },
    {
        id: 8,
        name: "Luxury Face Mask",
        category: "beauty",
        price: "€28,00",
        image: "http://static.photos/cosmetic/640x360/8",
        badge: null
    }
];

const testimonials = [
    {
        name: "Ana Silva",
        role: "Cliente VIP",
        text: "pt",
        image: "http://static.photos/people/200x200/1",
        textContent: {
            pt: "Os produtos da Welwitchia Style transformaram completamente minha rotina de beleza. A qualidade holandesa é evidente em cada detalhe.",
            en: "Welwitchia Style products have completely transformed my beauty routine. The Dutch quality is evident in every detail.",
            es: "Los productos de Welwitchia Style han transformado completamente mi rutina de belleza. La calidad holandesa es evidente en cada detalle.",
            nl: "Welwitchia Style producten hebben mijn schoonheidsroutine volledig getransformeerd. De Nederlandse kwaliteit is zichtbaar in elk detail.",
            de: "Die Produkte von Welwitchia Style haben meine Schönheitsroutine vollständig transformiert. Die holländische Qualität ist in jedem Detail erkennbar."
        }
    },
    {
        name: "Carlos Mendes",
        role: "Atleta Profissional",
        text: "pt",
        image: "http://static.photos/people/200x200/2",
        textContent: {
            pt: "Os suplementos de performance são de altíssima qualidade. Noto a diferença nos meus treinos desde o primeiro dia.",
            en: "The performance supplements are of the highest quality. I notice the difference in my workouts from day one.",
            es: "Los suplementos de rendimiento son de la más alta calidad. Noto la diferencia en mis entrenamientos desde el primer día.",
            nl: "De prestatiesupplementen zijn van de hoogste kwaliteit. Ik merk het verschil in mijn trainingen vanaf dag één.",
            de: "Die Leistungsergänzungsmittel sind von höchster Qualität. Ich bemerke den Unterschied in meinen Trainingseinheiten ab dem ersten Tag."
        }
    },
    {
        name: "Maria João",
        role: "Beauty Influencer",
        text: "pt",
        image: "http://static.photos/people/200x200/3",
        textContent: {
            pt: "Finalmente encontrei produtos premium em Angola com entrega rápida. O serviço é impecável!",
            en: "Finally found premium products in Angola with fast delivery. The service is impeccable!",
            es: "¡Finalmente encontré productos premium en Angola con entrega rápida. ¡El servicio es impecable!",
            nl: "Eindelijk premium producten gevonden in Angola met snelle levering. De service is onberispelijk!",
            de: "Endlich Premium-Produkte in Angola mit schneller Lieferung gefunden. Der Service ist tadellos!"
        }
    }
];

// State
let currentLang = 'pt';
let currentFilter = 'all';
let currentTestimonial = 0;

// Translations Object
const translations = {
    pt: {
        "nav.home": "Home",
        "nav.about": "Sobre",
        "nav.products": "Produtos",
        "nav.testimonials": "Depoimentos",
        "nav.contact": "Contacto",
        "hero.badge": "Premium Dutch Quality",
        "hero.title1": "Welwitchia",
        "hero.title2": "Style",
        "hero.subtitle": "Beleza Premium da Holanda para Angola e para o Mundo",
        "hero.cta1": "Explorar Produtos",
        "hero.cta2": "Conheça a Marca",
        "hero.stat1": "Holandês",
        "hero.stat2": "Países",
        "hero.stat3": "Clientes",
        "hero.stat4": "Rating",
        "about.subtitle": "Sobre Nós",
        "about.title": "Excelência Holandesa ao Seu Alcance",
        "about.badge": "Qualidade de Vida",
        "about.p1": "A Welwitchia Style nasceu da paixão por trazer o melhor da cosmética holandesa para Angola e o mundo. A Holanda, reconhecida pela Forbes como um dos melhores países para se viver, reflete essa excelência em cada produto que importamos.",
        "about.p2": "Selecionamos criteriosamente marcas premium que combinam inovação, sustentabilidade e resultados comprovados. Da beleza facial aos suplementos de performance, cada item em nosso catálogo representa o ápice da qualidade europeia.",
        "about.feature1.title": "Sustentável",
        "about.feature1.desc": "Produtos eco-friendly",
        "about.feature2.title": "Certificado",
        "about.feature2.desc": "Padrões europeus",
        "products.subtitle": "Catálogo",
        "products.title": "Nossos Produtos",
        "products.description": "Descubra nossa seleção premium de cosméticos e artigos de beleza importados diretamente da Holanda.",
        "filter.all": "Todos",
        "filter.cosmetics": "Cosméticos",
        "filter.beauty": "Beleza",
        "filter.gym": "Gym & Performance",
        "filter.wellness": "Bem-estar",
        "products.viewMore": "Ver Mais Produtos",
        "benefits.1.title": "Qualidade Holandesa",
        "benefits.1.desc": "Produtos importados diretamente dos melhores laboratórios dos Países Baixos, referência mundial em cosmética.",
        "benefits.2.title": "Entrega em Angola",
        "benefits.2.desc": "Logística eficiente garantindo que seus produtos premium cheguem em perfeitas condições a qualquer cidade.",
        "benefits.3.title": "Fórmulas Premium",
        "benefits.3.desc": "Ingredientes de alta performance, dermatologicamente testados e aprovados pelos padrões europeus mais rigorosos.",
        "testimonials.subtitle": "Depoimentos",
        "testimonials.title": "O Que Dizem Nossos Clientes",
        "contact.subtitle": "Contacto",
        "contact.title": "Vamos Conversar",
        "contact.description": "Entre em contacto connosco para encomendas, parcerias ou esclarecer dúvidas sobre nossos produtos premium.",
        "contact.address.title": "Angola & Internacional",
        "contact.address.desc": "Luanda, Angola | Entrega Mundial",
        "contact.email.desc": "Resposta em 24h",
        "contact.phone.desc": "Seg-Sex, 9h-18h",
        "contact.form.name": "Nome",
        "contact.form.email": "Email",
        "contact.form.message": "Mensagem",
        "contact.form.submit": "Enviar Mensagem",
        "footer.description": "Trazendo a excelência holandesa da cosmética premium para Angola e o mundo. Qualidade, sofisticação e resultados comprovados.",
        "footer.links.title": "Links",
        "footer.legal.title": "Legal",
        "footer.legal.privacy": "Privacidade",
        "footer.legal.terms": "Termos",
        "footer.legal.shipping": "Envios",
        "footer.rights": "Todos os direitos reservados.",
        "footer.madeWith": "Feito com",
        "footer.in": "em Angola & Holanda",
        "toast.title": "Mensagem Enviada!",
        "toast.message": "Entraremos em contacto em breve."
    },
    en: {
        "nav.home": "Home",
        "nav.about": "About",
        "nav.products": "Products",
        "nav.testimonials": "Testimonials",
        "nav.contact": "Contact",
        "hero.badge": "Premium Dutch Quality",
        "hero.title1": "Welwitchia",
        "hero.title2": "Style",
        "hero.subtitle": "Premium Beauty from the Netherlands to Angola and the World",
        "hero.cta1": "Explore Products",
        "hero.cta2": "Discover the Brand",
        "hero.stat1": "Dutch",
        "hero.stat2": "Countries",
        "hero.stat3": "Customers",
        "hero.stat4": "Rating",
        "about.subtitle": "About Us",
        "about.title": "Dutch Excellence Within Your Reach",
        "about.badge": "Quality of Life",
        "about.p1": "Welwitchia Style was born from the passion for bringing the best of Dutch cosmetics to Angola and the world. The Netherlands, recognized by Forbes as one of the best countries to live in, reflects this excellence in every product we import.",
        "about.p2": "We carefully select premium brands that combine innovation, sustainability, and proven results. From facial beauty to performance supplements, every item in our catalog represents the pinnacle of European quality.",
        "about.feature1.title": "Sustainable",
        "about.feature1.desc": "Eco-friendly products",
        "about.feature2.title": "Certified",
        "about.feature2.desc": "European standards",
        "products.subtitle": "Catalog",
        "products.title": "Our Products",
        "products.description": "Discover our premium selection of cosmetics and beauty items imported directly from the Netherlands.",
        "filter.all": "All",
        "filter.cosmetics": "Cosmetics",
        "filter.beauty": "Beauty",
        "filter.gym": "Gym & Performance",
        "filter.wellness": "Wellness",
        "products.viewMore": "View More Products",
        "benefits.1.title": "Dutch Quality",
        "benefits.1.desc": "Products imported directly from the best laboratories in the Netherlands, a world reference in cosmetics.",
        "benefits.2.title": "Delivery in Angola",
        "benefits.2.desc": "Efficient logistics ensuring your premium products arrive in perfect condition to any city.",
        "benefits.3.title": "Premium Formulas",
        "benefits.3.desc": "High-performance ingredients, dermatologically tested and approved by the most rigorous European standards.",
        "testimonials.subtitle": "Testimonials",
        "testimonials.title": "What Our Customers Say",
        "contact.subtitle": "Contact",
        "contact.title": "Let's Talk",
        "contact.description": "Get in touch with us for orders, partnerships, or to clarify questions about our premium products.",
        "contact.address.title": "Angola & International",
        "contact.address.desc": "Luanda, Angola | Worldwide Delivery",
        "contact.email.desc": "Reply within 24h",
        "contact.phone.desc": "Mon-Fri, 9am-6pm",
        "contact.form.name": "Name",
        "contact.form.email": "Email",
        "contact.form.message": "Message",
        "contact.form.submit": "Send Message",
        "footer.description": "Bringing Dutch excellence in premium cosmetics to Angola and the world. Quality, sophistication and proven results.",
        "footer.links.title": "Links",
        "footer.legal.title": "Legal",
        "footer.legal.privacy": "Privacy",
        "footer.legal.terms": "Terms",
        "footer.legal.shipping": "Shipping",
        "footer.rights": "All rights reserved.",
        "footer.madeWith": "Made with",
        "footer.in": "in Angola & Netherlands",
        "toast.title": "Message Sent!",
        "toast.message": "We will contact you soon."
    },
    es: {
        "nav.home": "Inicio",
        "nav.about": "Nosotros",
        "nav.products": "Productos",
        "nav.testimonials": "Testimonios",
        "nav.contact": "Contacto",
        "hero.badge": "Calidad Holandesa Premium",
        "hero.title1": "Welwitchia",
        "hero.title2": "Style",
        "hero.subtitle": "Belleza Premium de los Países Bajos para Angola y el Mundo",
        "hero.cta1": "Explorar Productos",
        "hero.cta2": "Conoce la Marca",
        "hero.stat1": "Holandés",
        "hero.stat2": "Países",
        "hero.stat3": "Clientes",
        "hero.stat4": "Valoración",
        "about.subtitle": "Sobre Nosotros",
        "about.title": "Excelencia Holandesa a tu Alcance",
        "about.badge": "Calidad de Vida",
        "about.p1": "Welwitchia Style nació de la pasión por traer lo mejor de la cosmética holandesa a Angola y el mundo. Los Países Bajos, reconocidos por Forbes como uno de los mejores países para vivir, reflejan esta excelencia en cada producto que importamos.",
        "about.p2": "Seleccionamos cuidadosamente marcas premium que combinan innovación, sostenibilidad y resultados comprobados. Desde la belleza facial hasta los suplementos de rendimiento, cada artículo en nuestro catálogo representa el pináculo de la calidad europea.",
        "about.feature1.title": "Sostenible",
        "about.feature1.desc": "Productos eco-friendly",
        "about.feature2.title": "Certificado",
        "about.feature2.desc": "Estándares europeos",
        "products.subtitle": "Catálogo",
        "products.title": "Nuestros Productos",
        "products.description": "Descubre nuestra selección premium de cosméticos y artículos de belleza importados directamente de los Países Bajos.",
        "filter.all": "Todos",
        "filter.cosmetics": "Cosméticos",
        "filter.beauty": "Belleza",
        "filter.gym": "Gym & Rendimiento",
        "filter.wellness": "Bienestar",
        "products.viewMore": "Ver Más Productos",
        "benefits.1.title": "Calidad Holandesa",
        "benefits.1.desc": "Productos importados directamente de los mejores laboratorios de los Países Bajos, referencia mundial en cosmética.",
        "benefits.2.title": "Entrega en Angola",
        "benefits.2.desc": "Logística eficiente garantizando que sus productos premium lleguen en perfectas condiciones a cualquier ciudad.",
        "benefits.3.title": "Fórmulas Premium",
        "benefits.3.desc": "Ingredientes de alto rendimiento, dermatológicamente probados y aprobados por los estándares europeos más rigurosos.",
        "testimonials.subtitle": "Testimonios",
        "testimonials.title": "Lo Que Dicen Nuestros Clientes",
        "contact.subtitle": "Contacto",
        "contact.title": "Hablemos",
        "contact.description": "Ponte en contacto con nosotros para pedidos, asociaciones o para aclarar dudas sobre nuestros productos premium.",
        "contact.address.title": "Angola & Internacional",
        "contact.address.desc": "Luanda, Angola | Entrega Mundial",
        "contact.email.desc": "Respuesta en 24h",
        "contact.phone.desc": "Lun-Vie, 9h-18h",
        "contact.form.name": "Nombre",
        "contact.form.email": "Email",
        "contact.form.message": "Mensaje",
        "contact.form.submit": "Enviar Mensaje",
        "footer.description": "Trayendo la excelencia holandesa en cosmética premium a Angola y el mundo. Calidad, sofisticación y resultados probados.",
        "footer.links.title": "Enlaces",
        "footer.legal.title": "Legal",
        "footer.legal.privacy": "Privacidad",
        "footer.legal.terms": "Términos",
        "footer.legal.shipping": "Envíos",
        "footer.rights": "Todos los derechos reservados.",
        "footer.madeWith": "Hecho con",
        "footer.in": "en Angola & Países Bajos",
        "toast.title": "¡Mensaje Enviado!",
        "toast.message": "Nos pondremos en contacto pronto."
    },
    nl: {
        "nav.home": "Home",
        "nav.about": "Over Ons",
        "nav.products": "Producten",
        "nav.testimonials": "Testimonials",
        "nav.contact": "Contact",
        "hero.badge": "Premium Nederlandse Kwaliteit",
        "hero.title1": "Welwitchia",
        "hero.title2": "Style",
        "hero.subtitle": "Premium Beauty uit Nederland voor Angola en de Wereld",
        "hero.cta1": "Ontdek Producten",
        "hero.cta2": "Ontdek het Merk",
        "hero.stat1": "Nederlands",
        "hero.stat2": "Landen",
        "hero.stat3": "Klanten",
        "hero.stat4": "Beoordeling",
        "about.subtitle": "Over Ons",
        "about.title": "Nederlandse Excellentie Binnen Handbereik",
        "about.badge": "Kwaliteit van Leven",
        "about.p1": "Welwitchia Style is geboren uit de passie om het beste van de Nederlandse cosmetica naar Angola en de wereld te brengen. Nederland, door Forbes erkend als een van de beste landen om in te wonen, weerspiegelt deze excellentie in elk product dat we importeren.",
        "about.p2": "We selecteren zorgvuldig premium merken die innovatie, duurzaamheid en bewezen resultaten combineren. Van gezichtsverzorging tot prestatiesupplementen, elk item in onze catalogus vertegenwoordigt het hoogtepunt van Europese kwaliteit.",
        "about.feature1.title": "Duurzaam",
        "about.feature1.desc": "Eco-vriendelijke producten",
        "about.feature2.title": "Gecertificeerd",
        "about.feature2.desc": "Europese standaarden",
        "products.subtitle": "Catalogus",
        "products.title": "Onze Producten",
        "products.description": "Ontdek onze premium selectie cosmetica en schoonheidsproducten direct geïmporteerd uit Nederland.",
        "filter.all": "Alle",
        "filter.cosmetics": "Cosmetica",
        "filter.beauty": "Schoonheid",
        "filter.gym": "Sportschool & Prestatie",
        "filter.wellness": "Welzijn",
        "products.viewMore": "Meer Producten Bekijken",
        "benefits.1.title": "Nederlandse Kwaliteit",
        "benefits.1.desc": "Producten direct geïmporteerd uit de beste laboratoria van Nederland, wereldreferentie in cosmetica.",
        "benefits.2.title": "Levering in Angola",
        "benefits.2.desc": "Efficiënte logistiek die garandeert dat uw premium producten in perfecte conditie in elke stad aankomen.",
        "benefits.3.title": "Premium Formules",
        "benefits.3.desc": "Hoogwaardige ingrediënten, dermatologisch getest en goedgekeurd volgens de strengste Europese normen.",
        "testimonials.subtitle": "Testimonials",
        "testimonials.title": "Wat Onze Klanten Zeggen",
        "contact.subtitle": "Contact",
        "contact.title": "Laten We Praten",
        "contact.description": "Neem contact met ons op voor bestellingen, partnerschappen of om vragen over onze premium producten te beantwoorden.",
        "contact.address.title": "Angola & Internationaal",
        "contact.address.desc": "Luanda, Angola | Wereldwijde Levering",
        "contact.email.desc": "Reactie binnen 24u",
        "contact.phone.desc": "Ma-Vr, 9u-18u",
        "contact.form.name": "Naam",
        "contact.form.email": "Email",
        "contact.form.message": "Bericht",
        "contact.form.submit": "Bericht Versturen",
        "footer.description": "Nederlandse excellentie in premium cosmetica naar Angola en de wereld brengen. Kwaliteit, verfijning en bewezen resultaten.",
        "footer.links.title": "Links",
        "footer.legal.title": "Juridisch",
        "footer.legal.privacy": "Privacy",
        "footer.legal.terms": "Voorwaarden",
        "footer.legal.shipping": "Verzending",
        "footer.rights": "Alle rechten voorbehouden.",
        "footer.madeWith": "Gemaakt met",
        "footer.in": "in Angola & Nederland",
        "toast.title": "Bericht Verstuurd!",
        "toast.message": "We nemen binnenkort contact met u op."
    },
    de: {
        "nav.home": "Home",
        "nav.about": "Über Uns",
        "nav.products": "Produkte",
        "nav.testimonials": "Bewertungen",
        "nav.contact": "Kontakt",
        "hero.badge": "Premium Niederländische Qualität",
        "hero.title1": "Welwitchia",
        "hero.title2": "Style",
        "hero.subtitle": "Premium Beauty aus den Niederlanden für Angola und die Welt",
        "hero.cta1": "Produkte Entdecken",
        "hero.cta2": "Marke Entdecken",
        "hero.stat1": "Niederländisch",
        "hero.stat2": "Länder",
        "hero.stat3": "Kunden",
        "hero.stat4": "Bewertung",
        "about.subtitle": "Über Uns",
        "about.title": "Niederländische Exzellenz in Reichweite",
        "about.badge": "Lebensqualität",
        "about.p1": "Welwitchia Style wurde aus der Leidenschaft geboren, das Beste der niederländischen Kosmetik nach Angola und in die Welt zu bringen. Die Niederlande, von Forbes als eines der besten Länder zum Leben anerkannt, spiegelt diese Exzellenz in jedem Produkt wider, das wir importieren.",
        "about.p2": "Wir wählen sorgfältig Premium-Marken aus, die Innovation, Nachhaltigkeit und bewährte Ergebnisse verbinden. Von Gesichtsbehandlung bis hin zu Leistungsergänzungsmitteln repräsentiert jeder Artikel in unserem Katalog den Gipfel der europäischen Qualität.",
        "about.feature1.title": "Nachhaltig",
        "about.feature1.desc": "Umweltfreundliche Produkte",
        "about.feature2.title": "Zertifiziert",
        "about.feature2.desc": "Europäische Standards",
        "products.subtitle": "Katalog",
        "products.title": "Unsere Produkte",
        "products.description": "Entdecken Sie unsere Premium-Auswahl an Kosmetik- und Schönheitsartikeln, direkt aus den Niederlanden importiert.",
        "filter.all": "Alle",
        "filter.cosmetics": "Kosmetik",
        "filter.beauty": "Schönheit",
        "filter.gym": "Fitness & Leistung",
        "filter.wellness": "Wellness",
        "products.viewMore": "Weitere Produkte",
        "benefits.1.title": "Niederländische Qualität",
        "benefits.1.desc": "Produkte direkt aus den besten Laboren der Niederlande importiert, weltweite Referenz in der Kosmetik.",
        "benefits.2.title": "Lieferung in Angola",
        "benefits.2.desc": "Effiziente Logistik, die sicherstellt, dass Ihre Premium-Produkte in jedem Stadtzentrum in perfektem Zustand ankommen.",
        "benefits.3.title": "Premium-Formeln",
        "benefits.3.desc": "Hochleistungszutaten, dermatologisch getestet und von den strengsten europäischen Standards zugelassen.",
        "testimonials.subtitle": "Bewertungen",
        "testimonials.title": "Was Unsere Kunden Sagen",
        "contact.subtitle": "Kontakt",
        "contact.title": "Lassen Sie Uns Sprechen",
        "contact.description": "Kontaktieren Sie uns für Bestellungen, Partnerschaften oder um Fragen zu unseren Premium-Produkten zu klären.",
        "contact.address.title": "Angola & International",
        "contact.address.desc": "Luanda, Angola | Weltweite Lieferung",
        "contact.email.desc": "Antwort innerhalb von 24h",
        "contact.phone.desc": "Mo-Fr, 9-18 Uhr",
        "contact.form.name": "Name",
        "contact.form.email": "E-Mail",
        "contact.form.message": "Nachricht",
        "contact.form.submit": "Nachricht Senden",
        "footer.description": "Wir bringen niederländische Exzellenz in Premium-Kosmetik nach Angola und in die Welt. Qualität, Raffinesse und bewährte Ergebnisse.",
        "footer.links.title": "Links",
        "footer.legal.title": "Rechtliches",
        "footer.legal.privacy": "Datenschutz",
        "footer.legal.terms": "AGB",
        "footer.legal.shipping": "Versand",
        "footer.rights": "Alle Rechte vorbehalten.",
        "footer.madeWith": "Gemacht mit",
        "footer.in": "in Angola & Niederlanden",
        "toast.title": "Nachricht Gesendet!",
        "toast.message": "Wir werden Sie bald kontaktieren."
    }
};

// Functions
function changeLanguage(lang) {
    currentLang = lang;
    document.getElementById('current-lang').textContent = lang.toUpperCase();
    document.documentElement.lang = lang;
    
    // Update all elements with data-i18n
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
    
    // Close dropdown
    document.getElementById('lang-dropdown').classList.remove('show');
    
    // Update testimonials
    renderTestimonials();
    
    // Re-render products to update any dynamic text
    renderProducts();
}

function toggleLanguageDropdown() {
    document.getElementById('lang-dropdown').classList.toggle('show');
}

function renderProducts() {
    const grid = document.getElementById('products-grid');
    const filtered = currentFilter === 'all' 
        ? products 
        : products.filter(p => p.category === currentFilter);
    
    grid.innerHTML = filtered.map(product => `
        <div class="product-card rounded-2xl overflow-hidden card-hover group">
            <div class="
